extends Resource

const SPECIAL_TAG_INFO := {
	"ritual":        { "text": "Used in Rituals", "color": Color.RED },
	"ritualsac":     { "text": "Used in Ritual Sacrifice", "color": Color.RED },
	"necro":         { "text": "Used in Necromantic Ways", "color": Color.RED },
	"rare":          { "text": "Part of a Rare Set", "color": Color.YELLOW },
	"evil":          { "text": "Emits a Sinister Aura", "color": Color(0.8, 0, 0.8) },
	"stopbleed":     { "text": "Stops Bleeding", "color": Color(0.2, 0.7, 0.2) },
	"healing":       { "text": "Restores Health", "color": Color(0.2, 0.8, 0.2) },
	"fishingbait":   { "text": "Used as Fishing Bait", "color": Color(0.1, 0.5, 0.1) },
	"firefuel":      { "text": "Burnable", "color": Color.DARK_GREEN },
	"light-tool":    { "text": "Provides light", "color": Color(0.8, 0.8, 0.1) },
	"crafting":      { "text": "Used in Crafting", "color": Color.DARK_GREEN },
	"ingredient":    { "text": "Used in Alchemy / Chemistry", "color": Color(0.2, 0.6, 0.2) },
	"smelt":         { "text": "May Be Smelted", "color": Color(0.3, 0.5, 0.3) },
	"raw":           { "text": "May be improved by Cooking", "color": Color(0.4, 0.7, 0.4) },
	"cooked":        { "text": "Prepared Food", "color": Color(0.4, 0.8, 0.4) },
	"edible":        { "text": "Safe to Eat", "color": Color(0.3, 0.7, 0.3) },
	"junk":          { "text": "Worthless Junk", "color": Color.GRAY },
	"metaljunk":     { "text": "Junk Metal", "color": Color.GRAY },
	"charming":      { "text": "Quite Charming", "color": Color(0.7, 0.6, 0.5) },
	"gorg":          { "text": "Simply Gorgeous", "color": Color(0.8, 0.8, 0.2) },
	"foulsmell":     { "text": "Unpleasant Odor", "color": Color(0.5, 0.4, 0.4) },
	"proper":        { "text": "Proper Garb for Upper Class Society", "color": Color(0.8, 0.8, 0.1) },
	"platearm":      { "text": "Heavy Plate Armor", "color": Color(0.7, 0.7, 0.1) },
	"lightboots":    { "text": "Flexible Light Boots", "color": Color(0.7, 0.7, 0.2) },
	"liquidcontainer": { "text": "May Hold Liquids", "color": Color(0.5, 0.7, 0.7) },
	"firearm":       { "text": "Firearm Weapon", "color": Color(0.8, 0.8, 0.1) },
	"ammo":       { "text": "Firearm Ammunition", "color": Color(0.8, 0.8, 0.1) },
	"wearable":      { "text": "Wearable", "color": Color(0.6, 0.6, 0.6) },
	"simplebag":     { "text": "Simple Bag", "color": Color(0.6, 0.6, 0.4) },
	"cutting":        { "text": "Cuts Through Material", "color": Color(0.7, 0.5, 0.4) },
	"concealable":   { "text": "Easy to Conceal", "color": Color(0.6, 0.6, 0.5) },
	"swift":          { "text": "Light & Swift", "color": Color(0.7, 0.7, 0.4) },
	"piercing":       { "text": "Pierces Armor", "color": Color(0.7, 0.4, 0.4) },
	"blunt":          { "text": "Blunt Force Impact", "color": Color(0.6, 0.5, 0.5) },
	"fishingtool":    { "text": "Useful for Fishing", "color": Color(0.2, 0.5, 0.2) },
	"impaling":       { "text": "Impaling Strike", "color": Color(0.7, 0.3, 0.3) },
	"harvest":         { "text": "Used for Harvesting", "color": Color(0.4, 0.6, 0.3) },
	"slashing":        { "text": "Slashing Attack", "color": Color(0.7, 0.3, 0.3) },
	"digging":         { "text": "Used for Digging", "color": Color(0.5, 0.6, 0.4) },
	"mining":           { "text": "Mining Tool", "color": Color(0.5, 0.5, 0.4) },
	"skinning":         { "text": "Used to Skin", "color": Color(0.6, 0.4, 0.4) },
	"tilling":           { "text": "Used to Till Soil", "color": Color(0.4, 0.5, 0.3) },
	"chopping":           { "text": "Used for Chopping Wood", "color": Color(0.5, 0.4, 0.3) },
	"luxury":               { "text": "A Status Symbol", "color": Color(0.9, 0.8, 0.2) },
	"lightsource":           { "text": "Provides Light", "color": Color(0.7, 0.7, 0.3) },
	"placeable":               { "text": "Can Be Placed", "color": Color(0.6, 0.6, 0.3) },
	"lockpick":                   { "text": "Used to Pick Locks", "color": Color(0.6, 0.6, 0.4) },
	"lock":                         { "text": "A Locking Object", "color": Color(0.5, 0.5, 0.5) },
	"key":                           { "text": "Unlocks Something", "color": Color(0.5, 0.5, 0.5) },
	"blueprint":                      { "text": "Learn a New Tech Wonder", "color": Color(0.6, 0.6, 0.7) },
	"readingmaterial":                   { "text": "Reading Material", "color": Color(0.6, 0.7, 0.7) },
	"sleepingsource":                        { "text": "Sleeping Source", "color": Color(0.6, 0.6, 0.4) },
	"legaltender":                           { "text": "Legal Tender", "color": Color(0.8, 0.7, 0.3) },
	"coveted":                               { "text": "Coveted by Criminals", "color": Color(0.9, 0.7, 0.2) },
	"tradegood":                             { "text": "Used in lieu of Currency", "color": Color(0.8, 0.6, 0.2) },
	"precious":                               { "text": "Precious and Valuable", "color": Color(1, 0.9, 0.4) },
	"trainingbook":                            { "text": "Training Manual", "color": Color(0.6, 0.7, 0.8) },
	"weirdfaithbook":                           { "text": "Strange Manuscript", "color": Color(0.5, 0.4, 0.7) },
	"unholyfaithbook":                             { "text": "Unholy Tome", "color": Color(0.7, 0.3, 0.5) },
	"holyfaithbook":                               { "text": "Holy Scripture", "color": Color(0.5, 0.7, 0.5) },
	"spellbook":                                    { "text": "A Mage's Personal Spellbook", "color": Color(0.7, 0.6, 0.8) },
	"jewelery":                                         { "text": "Jewelry", "color": Color(0.9, 0.8, 0.5) },
	##Objects/Terrain Tags
	"fireproof":      { "text": "Unaffected by Fire", "color": Color(1, 0.3, 0.3) },
	"flammable":      { "text": "Highly Flammable", "color": Color(1, 0.2, 0.2) },
	"lockable":       { "text": "Can Be Locked", "color": Color(0.6, 0.6, 0.7) },
	"badsleep":       { "text": "Uncomfortable for Sleeping", "color": Color(0.5, 0.3, 0.3) },
	"lightprovide":   { "text": "Emits Light", "color": Color(0.9, 0.9, 0.1) },
	"warmth":         { "text": "Provides Warmth", "color": Color(1, 0.5, 0.2) },
	"basiccooking":   { "text": "Basic Cooking Tool", "color": Color(0.6, 0.5, 0.3) },
	"workbench":      { "text": "Used as Workbench", "color": Color(0.4, 0.5, 0.3) },
	"craftingstation":{ "text": "Crafting Station", "color": Color.DARK_GREEN },
	"basiccraft":     { "text": "For Basic Crafting", "color": Color(0.3, 0.6, 0.3) },
	"chest":          { "text": "Storage Container", "color": Color(0.5, 0.4, 0.2) },
	"stinks":         { "text": "Smells Awful", "color": Color(0.6, 0.3, 0.3) },
	"mount":          { "text": "Can Be Ridden", "color": Color(0.7, 0.6, 0.2) },
	##Terrain Tags
	"tree":           { "text": "It's a Tree", "color": Color(0.3, 0.6, 0.3) },
	"grass":          { "text": "Tillable, Diggable for Worms", "color": Color(0.3, 0.8, 0.3) },
	"dirt":           { "text": "Tillable, Diggable for Worms", "color": Color(0.5, 0.4, 0.3) },
	"dirtywater":     { "text": "Unclean Water", "color": Color(0.4, 0.5, 0.5) },
	"dirtpath":       { "text": "Comfortable to walk on", "color": Color(0.6, 0.5, 0.3) },
	"bush":           { "text": "Cuttable for Plant Fiber", "color": Color(0.2, 0.7, 0.2) },
	"flowers":        { "text": "PCuttable for Plant Fiber", "color": Color(0.9, 0.6, 0.9) },
	"bridge":         { "text": "Comfortable to walk on", "color": Color(0.5, 0.5, 0.5) },
	"hole":           { "text": "Watch Your Step", "color": Color(0.3, 0.2, 0.2) },
	"stairs":         { "text": "Leads Somewhere", "color": Color(0.6, 0.6, 0.6) },
	"floor":          { "text": "Walkable Surface", "color": Color(0.4, 0.4, 0.4) },
	"wall":           { "text": "Structural Wall", "color": Color(0.3, 0.3, 0.3) },
	"windowwall":     { "text": "Can Peer Into", "color": Color(0.4, 0.4, 0.5) },
	"cavewall":       { "text": "Mine for stone", "color": Color(0.2, 0.2, 0.2) },
	##NPC Tags
	"simplefeline":   { "text": "A Simple Cat", "color": Color(0.7, 0.6, 0.5) },
	"simplesnake":    { "text": "A Simple Snake", "color": Color(0.6, 0.5, 0.4) },
	"magicuser":      { "text": "Knows Magic", "color": Color(0.6, 0.2, 0.8) },
	"musician":       { "text": "Musically Inclined", "color": Color(0.7, 0.6, 0.8) },
	"barter":         { "text": "Willing to Trade", "color": Color(0.8, 0.7, 0.2) },
	"traveller":      { "text": "A Wandering Soul", "color": Color(0.5, 0.6, 0.8) },
	"regularfolk":    { "text": "Just a Normal Person", "color": Color(0.6, 0.6, 0.6) }
}
