# terrain_data.gd
extends Node

const TERRAIN_PROPERTIES := {
	"tree": {
		"name": "Common Tree",
		"desc": "A common tree found in the wilderness.",
		"tags": ["tree"],
		"blocks_vision": false,
		"tree_chop": true,
		"burnable": true,
		"buildable": true,
		"blocks_movement": true,
		"chop_to": "dirt"
	},
	"tree2": {
		"name": "Common Tree",
		"desc": "A common tree found in the wilderness.",
		"tags": ["tree"],
		"blocks_vision": false,
		"tree_chop": true,
		"burnable": true,
		"buildable": true,
		"blocks_movement": true,
		"chop_to": "dirt"
	},
	"tree3": {
		"name": "Common Tree",
		"desc": "A common tree found in the wilderness.",
		"tags": ["tree"],
		"blocks_vision": false,
		"tree_chop": true,
		"burnable": true,
		"buildable": true,
		"blocks_movement": true,
		"chop_to": "dirt"
	},
	"grass": {
		"name": "Patch of grass",
		"desc": "a typical patch of grassland",
		"tags": ["grass"],
		"blocks_vision": false,
		"grass_cut": true,
		"grass_search": true,
		"diggable": true,
		"burnable": true,
		"blocks_movement": false,
		"dig_to": "dirt"
	},
	"dirt": {
		"name": "Patch of dirt",
		"desc": "a typical patch of dirt",
		"tags": ["dirt"],
		"blocks_vision": false,
		"diggable": true,
		"hoeable": true,
		"blocks_movement": false,
		"dig_to": "hole"
	},
	"water": {
		"name": "Water",
		"desc": "A bit of natural water, I could fish or collect dirty water here",
		"tags": ["dirtywater"],
		"blocks_vision": false,
		"fishable": true,
		"drinkable": true,
		"pottable": true,
		"pottable_liquid": "dirty_water",
		"wet": true,
		"block_building": true,
		"blocks_movement": false
	},
	"path": {
		"name": "Dirt Path",
		"desc": "Someone has beaten a path here",
		"tags": ["dirtpath"],
		"blocks_vision": false,
		"blocks_movement": false
	},
	"bush": {
		"name": "Bush",
		"desc": "An overgrown patch of weeds grows here",
		"tags": ["bush"],
		"blocks_vision": false,
		"bush_cut": true,
		"bush_search": true,
		"burnable": true,
		"blocks_movement": false,
		"block_building": true,
		"destroy_to": "dirt"
	},
	"flowers": {
		"name": "Flowers",
		"desc": "A patch of lovely flowers grows here",
		"tags": ["flowers"],
		"blocks_vision": false,
		"flowers_cut": true,
		"flowers_search": true,
		"burnable": true,
		"blocks_movement": false,
		"block_building": true,
		"destroy_to": "dirt"
	},
	"bridge": {
		"name": "Wood Bridge",
		"desc": "Someone has built a wooden bridge here",
		"tags": ["bridge"],
		"blocks_vision": false,
		"wood_destroy": true,
		"burnable": true,
		"blocks_movement": false,
		"destroy_to": "water"
	},
	"hole": {
		"name": "Cave Entrance",
		"desc": "A hole leading into the earth, what awaits me down there?",
		"tags": ["hole"],
		"blocks_vision": false,
		"hole_enter": true,
		"hole_spawn": true,
		"block_building": true,
		"blocks_movement": false
	},
	"stonefloor": {
		"name": "Stone Floor",
		"desc": "Rustic Cobblestone Flooring",
		"tags": ["floor", "fireproof"],
		"blocks_vision": false,
		"stone_destroy": true,
		"destroy_to": "dirt",
		"indoor_floor": true,
		"buildable": true,
		"blocks_movement": false
	},
	"stairs": {
		"name": "Stairs",
		"desc": "Stairs leading where?",
		"tags": ["stairs"],
		"blocks_vision": false,
		"stairs_enter_down": true,
		"buildable": true,
		"block_building": true,
		"blocks_movement": false
	},
	"stonewallside": {
		"name": "Stone Wall",
		"desc": "Rustic Cobblestone Wall",
		"tags": ["wall", "fireproof"],
		"blocks_vision": true,
		"stone_destroy": true,
		"destroy_to": "dirt",
		"indoor_wall": true,
		"buildable": true,
		"blocks_movement": true
	},
	"stonewallbottom": {
		"name": "Stone Wall",
		"desc": "Rustic Cobblestone Wall",
		"tags": ["wall", "fireproof"],
		"blocks_vision": true,
		"stone_destroy": true,
		"destroy_to": "dirt",
		"indoor_wall": true,
		"buildable": true,
		"blocks_movement": true
	},
	"stonewallbottomwindow": {
		"name": "Stone Wall Window",
		"desc": "Rustic Cobblestone Wall with a Window",
		"tags": ["windowwall", "fireproof"],
		"blocks_vision": false,
		"window": true,
		"openable_window": true,
		"has_curtains": true,
		"starts_closed": true,
		"breakable": true,
		"stone_destroy": true,
		"destroy_to": "dirt",
		"indoor_wall": true,
		"buildable": true,
		"blocks_movement": true
	},
	"stonewallsidewindow": {
		"name": "Stone Wall Window",
		"desc": "Rustic Cobblestone Wall with a Window",
		"tags": ["windowwall", "fireproof"],
		"blocks_vision": false,
		"window": true,
		"openable_window": true,
		"has_curtains": true,
		"starts_closed": true,
		"breakable": true,
		"stone_destroy": true,
		"destroy_to": "dirt",
		"indoor_wall": true,
		"buildable": true,
		"blocks_movement": true
	},
	"short_ladder": {
		"name": "Ladder",
		"desc": "Rustic Ladder, leading where?",
		"tags": ["ladder"],
		"blocks_vision": false,
		"stairs_enter_up": true,
		"buildable": true,
		"block_building": true,
		"blocks_movement": false
	},
	"long_ladder": {
		"name": "Ladder",
		"desc": "Rustic Ladder, leading where?",
		"tags": ["ladder"],
		"blocks_vision": false,
		"stairs_enter_up": true,
		"buildable": true,
		"block_building": true,
		"blocks_movement": false
	},
	"stonedoor": {
		"name": "Stone Door",
		"desc": "Simple stone door made from primitive materials.",
		"tags": ["lockable", "fireproof"],
		"blocks_vision": true,
		"door": true,
		"openable_door": true,
		"starts_closed": true,
		"stone_destroy": true,
		"buildable": true,
		"destroy_to": "dirt",
		"indoor_wall": true,
		"block_building": true,
		"blocks_movement": true
	},
	"slum_road_floor": {
		"name": "Dirty Street",
		"desc": "Poorly maintained paved street for vehicle traffic",
		"tags": ["floor", "fireproof"],
		"blocks_vision": false,
		"blocks_movement": false
	},
	"slum_sidewalk_floor": {
		"name": "Dirty Sidewalk",
		"desc": "Poorly maintained sidewalk for foot traffic",
		"tags": ["floor", "fireproof"],
		"blocks_vision": false,
		"blocks_movement": false
	},
	"slum_brick_floor": {
		"name": "Brick Floor",
		"desc": "Old tenament flooring",
		"tags": ["floor", "fireproof"],
		"blocks_vision": false,
		"stone_destroy": true,
		"destroy_to": "dirt",
		"indoor_floor": true,
		"buildable": true,
		"blocks_movement": false
	},
	"slum_stone_floor": {
		"name": "Stone Floor",
		"desc": "Unremarkable flooring",
		"tags": ["floor", "fireproof"],
		"blocks_vision": false,
		"stone_destroy": true,
		"destroy_to": "dirt",
		"indoor_floor": true,
		"buildable": true,
		"blocks_movement": false
	},
	"slum_brick_wallside": {
		"name": "Brick Wall",
		"desc": "Old tenament wall",
		"tags": ["wall", "fireproof"],
		"blocks_vision": true,
		"stone_destroy": true,
		"destroy_to": "dirt",
		"indoor_wall": true,
		"buildable": true,
		"blocks_movement": true
	},
	"slum_brick_wallbottom": {
		"name": "Brick Wall",
		"desc": "Old tenament wall",
		"tags": ["wall", "fireproof"],
		"blocks_vision": true,
		"stone_destroy": true,
		"destroy_to": "dirt",
		"indoor_wall": true,
		"buildable": true,
		"blocks_movement": true
	},
	"slum_brick_wallbottom_window": {
		"name": "Brick Wall with Window",
		"desc": "Old tenament wall with window",
		"tags": ["windowwall", "fireproof"],
		"blocks_vision": false,
		"window": true,
		"openable_window": true,
		"has_curtains": true,
		"starts_closed": true,
		"breakable": true,
		"stone_destroy": true,
		"destroy_to": "dirt",
		"indoor_wall": true,
		"buildable": true,
		"blocks_movement": true
	},
	"slum_brick_wallside_window": {
		"name": "Brick Wall with Window",
		"desc": "Old tenament wall with window",
		"tags": ["windowwall", "fireproof"],
		"blocks_vision": false,
		"window": true,
		"openable_window": true,
		"has_curtains": true,
		"starts_closed": true,
		"breakable": true,
		"stone_destroy": true,
		"destroy_to": "dirt",
		"indoor_wall": true,
		"buildable": true,
		"blocks_movement": true
	},
	"slum_brick_door": {
		"name": "Old wood door in Brick Wall",
		"desc": "Old tenament door with scrapped corners",
		"tags": ["lockable", "fireproof"],
		"blocks_vision": true,
		"door": true,
		"openable_door": true,
		"starts_closed": true,
		"stone_destroy": true,
		"buildable": true,
		"destroy_to": "dirt",
		"indoor_wall": true,
		"blocks_movement": true
	},
	"slum_brick_floor_stairs_down": {
		"name": "Old tenament stairs",
		"desc": "Simple stairs in an old building",
		"tags": ["stairs", "fireproof"],
		"blocks_vision": false,
		"stairs_enter_down": true,
		"buildable": true,
		"blocks_movement": false
	},
	"slum_brick_floor_stairs_up": {
		"name": "Old tenament stairs",
		"desc": "Simple stairs in an old building",
		"tags": ["stairs", "fireproof"],
		"blocks_vision": false,
		"stairs_enter_up": true,
		"buildable": true,
		"blocks_movement": false
	},	
	"stonefloor_hole": {
		"name": "Crumbling Hole in Stone Flooring",
		"desc": "It appears the floor collapsed here, leading somewhere.",
		"tags": ["hole"],
		"blocks_vision": false,
		"stairs_enter_down": true,
		"buildable": true,
		"block_building": true,
		"blocks_movement": false
	},	
	"slum_wood_fence": {
		"name": "Old slum fencing",
		"desc": "Blocks your vision but ugly and flimsy",
		"tags": ["wall"],
		"blocks_vision": true,
		"wood_destroy": true,
		"destroy_to": "dirt",
		"indoor_wall": true,
		"buildable": true,
		"block_building": true,
		"blocks_movement": true
	},
	"cavewallbottom": {
		"name": "Cave Wall",
		"desc": "Natural cavern walls",
		"tags": ["cavewall"],
		"blocks_vision": true,
		"stone_destroy": true,
		"destroy_to": "dirt",
		"indoor_wall": true,
		"buildable": true,
		"blocks_movement": true
	},
	"cavewallside": {
		"name": "Cave Wall",
		"desc": "Natural cavern walls",
		"tags": ["cavewall"],
		"blocks_vision": true,
		"stone_destroy": true,
		"destroy_to": "dirt",
		"indoor_wall": true,
		"buildable": true,
		"blocks_movement": true
	}
}
